### ISSUE TITLE
Adapt ViewModel name to include View only once

### ISSUE THREAD

**Issue by janschreier** [PrismLibrary/Prism.Templates#18]
## Summary

Currently when you create a View with it's name ending on VIew the ViewModel ist ViewViewModel.  Which feels a bit clumsy, at least to me. I think you mentioned that this could be changed in one of the latest, streams, Brian.

This seems to be a good case for a first-issue. But I thought I just ask what your opinion is about this before I create a PR :)

**Comment by dansiegel** [comment]
@janschreier the functionality you're talking about is part of the VSIX which is in a private repo. I've assigned the issue to @brianlagunas for him to look into and fix hopefully in the next release of the VS Extension

**Comment by brianlagunas** [comment]
I'm glad you said something @dansiegel, I had no idea what this meant. I thought this was related to the ViewModelLocator

**Comment by brianlagunas** [comment]
This has been fixed
