### ISSUE TITLE
Prism Project Template using only DryIoc container in .Net Core WPF Applications

### ISSUE THREAD

**Issue by arlvin** [PrismLibrary/Prism.Templates#25]
## Summary
When i select the "Prism Full App (.Net Core)" project template in Visual Studio 2019 and then select Unity as my dependency injection container, the solution created uses the DryIoc dependency injection container instead. This is in .NET Core 3.1.

## Intended Use Case
In my particular project i wanted to use Unity as my dependency injection container and i'm sure there may be other developers with that preference.

**Comment by brianlagunas** [comment]
Yup, I know about this. Just been to busy too fix. I'll get to it one day, unless you want to put a PR together for me 😄

**Comment by brianlagunas** [comment]
This has been fixed

**Comment by arlvin** [comment]
:thumbsup:
