### ISSUE TITLE
Error when adding new Views to project

### ISSUE THREAD

**Issue by mjphillips1981** [PrismLibrary/Prism.Templates#26]
## Summary

When I add a new view to my project using the Prism Templates a Fail to Run wizard error pops up.  Error message: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))  

Everything seems to be working other than if I open the XAML file right after this error it crashes VS2019 v16.7.3.  Once reopening the project views and viewmodels are there and working properly.  I have tried a reinstall of the templates packet and still gives the error.  Just letting you know.  

## Intended Use Case

n/a

**Comment by brianlagunas** [comment]
What view and what kind of project?

**Comment by mjphillips1981** [comment]
I am running a Prism xamarin.forms project using Prism magician. And any of the views I try, will produce the same issue.

**Comment by brianlagunas** [comment]
@mjphillips1981 Have you tested without Magician? As you may know, Magician is not a supported here.

**Comment by dansiegel** [comment]
@brianlagunas the Magician wouldn't have any effect there... the error seems to be happening in the VS Template Wizard

**Comment by mjphillips1981** [comment]
@brianlagunas I have not since the error has happened.  I will try an create a new project now. And report back.

**Comment by mjphillips1981** [comment]
Just did a test.  If I create a new Prism Blank App from the template everything works as it should when adding new views.  But if I try and add a view from a Xamarin.Forms blank project I get the error.

**Comment by brianlagunas** [comment]
That's because you can't add Prism templates to a standard Xamarin.Forms app. It doesn't make sense to even try. This is not supported.

**Comment by mjphillips1981** [comment]
ok, I will keep that in mind.  this was a project a that I had already created and manually changed to Prism app.

**Comment by brianlagunas** [comment]
That should work. It has to be a Prism app though. Attach a repro app and I'll look into it.
