### ISSUE TITLE
There are no Snippets

### ISSUE THREAD

**Issue by liuke-wuhan** [PrismLibrary/Prism.Templates#33]
## Summary

Please provide a brief summary of your proposal. Two to three sentences is best here.

## Intended Use Case

Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by brianlagunas** [comment]
No there are not

**Comment by hongjiapeng** [comment]
This means that I want to make Prism's code snippets more convenient to use, can't I change it in this repository? @brianlagunas

**Comment by dansiegel** [comment]
@hongjiapeng the snippets are part of the VS Tooling and are not public

**Comment by hongjiapeng** [comment]
> @hongjiapeng the snippets are part of the VS Tooling and are not public

ok,thank you
