### ISSUE TITLE
[Bug] Blank Prism App (WPF) template not creating a working project.

### ISSUE THREAD

**Issue by JaINTP** [PrismLibrary/Prism.Templates#34]
### Description
Hey there. I have recently installed the template pack extension, and I managed to create one working test project, however ever since I've run into the same problem repeatedly, where creating a new project using a template doesn't bring up the wizard, which seems to default to Dryloc, and I end up with an empty solution. The projects are there physically. but are unloadable.

 I tried fixing the error that is presented by modifying the TargetFrameworkVersion and removing the duplicate v, which allows the project to be loaded, but then I run into errors regarding Dryloc and the .Net version.
 
 Fresh Visual Studio installation and fresh template installation. Have reinstalled the template pack multiple times but to no avail.
 
### Steps to Reproduce

1. Open Visual Studio
2. Create new Blank Prism Project using template
3. Name project
4. Run into problems

### Expected Behaviour
Fresh working Prism project should be created.

### Actual Behaviour
Broken project is created.

### Basic Information
Version with issue: Prism Template Pack 2.3.0
Last known good version: Unsure
IDE: Visual Studio 2019 Community

### Screenshots
Without modifying the csproj file this error comes up when attempting to add it to the solution:
![03-05-2021_11-21-54_Microsoft_Visual_Studio](https://user-images.githubusercontent.com/4857160/116834533-e2814700-ac01-11eb-9329-bd1eee186163.png)

A gif reproducing the problem:
![03-05-2021_11-24-40_%t](https://user-images.githubusercontent.com/4857160/116834688-8e2a9700-ac02-11eb-9d50-b61ed6152dbe.gif)

**Comment by brianlagunas** [comment]
This just means VS broke something again. I'll look into it when I get a chance.

**Comment by DamianSuess** [comment]
@brianlagunas I was taking a look into this a couple of weeks ago thinking it was a "quick fix". However, I wasn't sure of a couple of things.
1. Which VS versions do you guys want to support for backward compatibility? - _2017 and 2019, or 2019 only?_
2. Which iteration of v16.x did this breaking change occur? - _I'm still digging around when free time allows._

If this was strictly "_newer VS versions_" only I was going to just remove the 'v' in the template and call it a day.

**Comment by brianlagunas** [comment]
The template pack has been updated and everything should work now.
