### ISSUE TITLE
Databinding not working for UNO template

### ISSUE THREAD

**Issue by DanielEggers** [PrismLibrary/Prism.Templates#35]
Creating a blank UNO solution for WASM the Titel property of the ViewModelBase is not displayed in the Shell.xaml 

`    <StackPanel Margin="20">
      <TextBlock Text="{Binding Title}" FontSize="30" />
      <TextBlock Text="{Binding Description}" FontSize="30" />
      <TextBlock Text="Welcome to Uno/WinUI and Prism!" FontSize="15" />
    </StackPanel>`

Maybe I am just missing something, but I think this should work out of the box.

If I add a property (Description) to the ShellViewModel it is displayed. So it looks like the ViewModelLocator is not recognizing properties in another assembly or base class.

**Comment by dansiegel** [comment]
This is neither a bug with the Template or something for which the Prism team has any control over. You should report the bug either the Uno team or in Visual Studio
