### ISSUE TITLE
Implement x:DataType="MyViewModel" on create new Prism ContentPage

### ISSUE THREAD

**Issue by LeoJHarris** [PrismLibrary/Prism.Templates#36]
It would be nice to have support when generating the view, view-model and register in IOC through the prism template pack to automatically set the X:DataType to the view-model generated also.

As intellisense has improved in Xaml it would be nice to take advantage of this through the prism template pack and assign this the viewmodel when created

**Comment by brianlagunas** [comment]
I'm not really sure what you mean by x:DataType but design time data is not something Prism is going to be responsible for.

**Comment by LeoJHarris** [comment]
@brianlagunas Hi Brian, its as part of the compiled-bindings. 

For example on a given page that is using the MVVM approach its normally the ViewModel for the page as shown below. 

![image](https://user-images.githubusercontent.com/5468757/165653582-5d72caea-9e51-4ab3-a7bb-ee7c905e6b8e.png)

Assigning x:DataType will improves intellisense in XAML files and surfaces a compile time error  "Member not found in data context [BindingContext]" if Binding not set correctly.

It’s good practice to set the x:DataType attribute at the same level in the view hierarchy as the [BindingContext].

No worries though! Thanks for your efforts!
