### ISSUE TITLE
Prism template pack does not support visual studio 2022

### ISSUE THREAD

**Issue by Yuexs** [PrismLibrary/Prism.Templates#39]
Prism template pack does not support visual studio 2022

Expect update support

**Comment by Blackhawk50000** [comment]
@brianlagunas 
it can not be closed.... the issu you linked is closed because of a wrong repo and AND it is linked to THIS issue. (circle)
one of this has to be open =)

**Comment by brianlagunas** [comment]
@Blackhawk50000 this issue isn't closed 😄

**Comment by Blackhawk50000** [comment]
> 

Oh, now i understand... the Closed Status is from the other issue in the wrong repo. i am so sorry....

**Comment by codebreakerlegend2019** [comment]
Any Updates from this one?

**Comment by brianlagunas** [comment]
Nope, still haven't made time for this 🤷

**Comment by xiurobert** [comment]
Temporary workaround if you're trying to create a module:

Create a .NET/.NET Core Class Library and install the NuGet packages yourself

**Comment by maxchu92** [comment]
Try using this. This is a temporary solution by changing the version in _extension.vsixmanifest_ and rezip it into .vsix. Some features like auto creating a ViewModel file when you are creating a XAML page doesn't work. U had to add the ViewModel manually.

[PrismTemplatePack 2022.zip](https://github.com/PrismLibrary/Prism.Templates/files/8194824/PrismTemplatePack.2022.zip)

**Comment by utech626** [comment]
@brianlagunas if you upload the VISX project I'll be happy to convert it over to a VS 2019/2022 project

**Comment by 9nix6** [comment]
@brianlagunas please recompile Prism.VisualStudio.Wizards.dll in VS2022 with the latest package references. That will suffice along with the temporary solution by @maxchu92 

Use:

    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.1.32210.191" />
    <PackageReference Include="Microsoft.VisualStudio.TemplateWizardInterface" Version="17.1.32210.191" />

instead of:

    <Reference Include="EnvDTE" />
    <Reference Include="Microsoft.VisualStudio.OLE.Interop" />
    <Reference Include="Microsoft.VisualStudio.Shell.Interop" />
    <Reference Include="Microsoft.VisualStudio.TemplateWizardInterface" />

This will only take a few moments and prism users will finally be able to utilize the template pack in VS2022.

[How to update a Visual Studio extension for Visual Studio 2022](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022)

**Comment by brianlagunas** [comment]
FYI... I'm working on this now. Since vs2019 and vs2022 extensions are incompatible, I will only be supporting the latest version of VS.

**Comment by brianlagunas** [comment]
Does anyone have VS2019 installed and willing to test the new Prism Template Pack? VS2022 makes it difficult for backwards compat, and just want to test to make sure it is.

[PrismTemplatePack.zip](https://github.com/PrismLibrary/Prism.Templates/files/8578048/PrismTemplatePack.zip)

If it's not, then only VS2022 will be supported 😄 

Please let me know if it works, or doesn't work so I can update the VSIX targets if needed.

Thanks

**Comment by utech626** [comment]
@brianlagunas  vsix only prompts for installation in 2022

**Comment by brianlagunas** [comment]
@utech626 try this one
[PrismTemplatePack.zip](https://github.com/PrismLibrary/Prism.Templates/files/8578110/PrismTemplatePack.zip)

**Comment by utech626** [comment]
@brianlagunas  installs in 2019 when trying to create project following error: 
then vstemplate file references wizard class 'Prism.VisualStudio.Wizards.SelectCotainerWizards, version 1.0.0.0 ...

**Comment by brianlagunas** [comment]
@utech626 Which template are you using?

**Comment by utech626** [comment]
@brianlagunas The Prism WPF full template

**Comment by brianlagunas** [comment]
@utech626 not sure what's going on there. The code is right 
![image](https://user-images.githubusercontent.com/835562/165641716-b7ef58db-7572-449e-a034-ca7a575ddfc3.png)

**Comment by utech626** [comment]
@brianlagunas the first zip that installed, I created a 2022 WPF Full App, Compiled it ran it and ran the Unit test all thumbs up

**Comment by brianlagunas** [comment]
@utech626 Yeah, I'm afraid it's a backwards compat issue in the wizard. Oh well. VS2022 it is 😄 

I'll get the update on the marketplace soon

**Comment by utech626** [comment]
@brianlagunas  thank you sir

**Comment by brianlagunas** [comment]
The Prism Template Pack now support VS2022!!!

**Comment by wuhongjun15** [comment]
what should I do if I want use it with VS2019?

**Comment by dansiegel** [comment]
Realize it's about as supported as VS2013

**Comment by h1nson** [comment]
VS2019 can not install the latest version.  About old version the xamarin.forms version in the tempalte is too old.

**Comment by CzBuCHi** [comment]
@brianlagunas hey nice work! i was waiting for this loong time :)

BTW: [this blog post](https://cezarypiatek.github.io/post/migrate-vsix-to-vs2022/) has some nice ideas how to build vsix for VS2019 and VS2022 so you can still support older visual studio ...

**Comment by brianlagunas** [comment]
I know how to support vs2019, I just don’t want to.
