### ISSUE TITLE
Prism.Template is not showing up on VS2015.

### ISSUE THREAD

**Issue by hemantnavarkar** [PrismLibrary/Prism.Templates#40]
## Summary

Run the VS2015
Go to Tools->Extensio and Updates
Go to the Online tab, on Left-hand side
Try to search Prism Template Pack, but no search result was found.

![image](https://user-images.githubusercontent.com/8719447/141674262-39940f15-fa96-4e0b-a49a-eec9ec283522.png)

## Intended Use Case

Should find thee extension.

**Comment by brianlagunas** [comment]
VS2015 is not supported
