### ISSUE TITLE
Add a Prism Xamarin Full App template that includes regions

### ISSUE THREAD

**Issue by bakerhillpins** [PrismLibrary/Prism.Templates#41]
## Summary

Add a Prism Xamarin Forms template based off of the Prism Full App (.NET Core) template.  This provides a full example of a Prism application using Regions as well as testing.

## Intended Use Case

Helps folks start a full Xamarin Forms Prism application including proper setup for Region use.

**Comment by bakerhillpins** [comment]
I ported over the project to help me understand region use so why not add it to the templates.  I do have the [following question](https://github.com/PrismLibrary/Prism/discussions/2644) regarding startup design that probably should be considered as part of this. 

I started a [PR](https://github.com/PrismLibrary/Prism.Templates/pull/42) for this too.

**Comment by dansiegel** [comment]
I realize that you've already put up a PR for this as well. @brianlagunas and I will discuss this when we get a chance. TBH it may be a bit as he's been on vacation and will likely need some time to catch up before he can dedicate some time on this.

**Comment by bakerhillpins** [comment]
@dansiegel  NP on timing. I'm working on understanding regions by building out some simple code right now anyway. With any luck I could roll that into the samples too.

Thanks for the communication!

**Comment by dansiegel** [comment]
closing as discussed in #42
