### ISSUE TITLE
Upgrade NuGet packages to Prism 8.1.97

### ISSUE THREAD

**Issue by DamianSuess** [PrismLibrary/Prism.Templates#43]
## Summary

As a user, I would like the Prism Templates to use the latest version of the software, v8.1.97 (previously, 8.0.0).  This also includes the latest Uno, Xamarin.Forms, and Xamarin.Essentials.Interfaces. 

## Intended Use Case

This keeps the templates up-to-date and reduces the time to fetch the latest packages during prototyping.

Thank you and Happy New Year, Brian/Dan!
-- Damian (aka. SuessLabs)

**Comment by dansiegel** [comment]
closed by #44
