### ISSUE TITLE
Issue in Main.cs source file in the Tizen platform artifacts of the Prism Maui templates

### ISSUE THREAD

**Issue by egvijayanand** [PrismLibrary/Prism.Templates#49]
## Summary

Referring to the Main.cs source file in the Tizen platform artifacts of the Prism Maui templates. The startup method is pointing to something that is not available. Refer to the attached screenshot for details.

![image](https://user-images.githubusercontent.com/81947404/171939408-33c33815-86ac-4c89-a9e7-205e321f7db7.png)

## Intended Use Case

Improve the stability of the published templates.

**Comment by egvijayanand** [comment]
And also the project name is not properly replaced in the tizen-manifest.xml file.

It's still pointing to `PrismApp1`, which is causing a build error.

**Comment by dansiegel** [comment]
fixed by #50
