### ISSUE TITLE
Migrate the WPF project to SDK Style

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism.Templates#6]
The Full Framework WPF Project template currently uses the legacy style project format. This should be updated to use the newer SDK Style format while preserving the ability to select the framework version.

**Comment by WaldemarCoding** [comment]
@dansiegel is this something you are going to do while building the FullApp-Template or could I give it a try?

**Comment by brianlagunas** [comment]
This has been implemented
