### ISSUE TITLE
List of changes to make project even better!

### ISSUE THREAD

**Issue by ysmoradi** [PrismLibrary/Prism.Templates#7]
1- Add Xamarin Essentials
2- Set DebugType and DebugSymbols to true for Debug builds
3- Use Android 10 SDK & Android X
4- Use Aapt2 in android
5- Use d8 in android
6- Enable concurrent garbage collector in android
7- Remove Xamarin.Android.Support.* nuget packages
8- Enable Mono interpreter for debug mode of iOS project.

I'm open to submit a PR to any of these changes which are acceptable by the Prism team too.

**Comment by dansiegel** [comment]
Well your 3 and 7 is a duplication of issue #4 so we’re good there. Really these are all valid issues. We’d be happy to take a PR for 3-8. 

For the other two let’s open an issue for each of them to track and discuss individually.

**Comment by ysmoradi** [comment]
So, just to make sure that I'm getting things correctly, I can submit a PR for 3-8 and I should open an issue for 1&2
